# Generated by Django 3.0.5 on 2020-04-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
    ]
